version: "3.1"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - blockchian
    volumes:
      - ./frontend:/app
    command: npm run dev

  blockchian:
    build:
      context: ./blockchain
    ports:
      - 8545:8545
    volumes:
      - ./blockchain:/app
    command: npm run node

  backend:
    build:
      context: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    depends_on:
      - database
    env_file:
      - ./.env.dev
    command: sh -c "npm run migrate:dev && npm start"

  database:
    image: postgres:15.4-alpine3.18
    restart: always
    volumes:
      - /var/lib/postgresql
    env_file:
      - ./.env.dev
    ports:
      - "${DB_PORT}:5432"
